# Generated by Django 6.0.3 on 2026-03-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=50)),
                ('song_genre', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('heavy_metal', 'Heavy_metal'), ('soft_rock', 'Soft_rock'), ('pop_rock', 'Pop_rock'), ('country', 'Country')], default='pop', max_length=20)),
                ('song_mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('romantic', 'Romantic'), ('angry', 'Angry'), ('energetic', 'ENERGETIC'), ('calm', 'Calm')], default='happy', max_length=20)),
                ('song_base_singer', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prompt',
                'ordering': ['created_at'],
            },
        ),
    ]
