# Generated by Django 6.0.3 on 2026-04-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0003_prompt_generation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='generation_status',
        ),
        migrations.AddField(
            model_name='prompt',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
