# Generated by Django 6.0.3 on 2026-04-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0004_remove_prompt_generation_status_prompt_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='generation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TEXT_SUCCESS', 'Text Success'), ('FIRST_SUCCESS', 'First Success'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='PENDING', max_length=20),
        ),
    ]
