# Generated by Django 6.0.3 on 2026-04-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='song_base_singer',
        ),
    ]
