# Generated by Django 6.0.3 on 2026-04-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0002_remove_prompt_song_base_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='generation_status',
            field=models.CharField(choices=[('generating', 'Generating'), ('generated', 'Generated'), ('error', 'Error')], default='generating', max_length=20),
        ),
    ]
