# Generated by Django 6.0.3 on 2026-03-21 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('prompt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=50)),
                ('shared_link', models.CharField(blank=True, max_length=255, null=True)),
                ('sharing_status', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20)),
                ('generation_status', models.CharField(choices=[('generating', 'Generating'), ('generated', 'Generated'), ('error', 'Error')], default='generating', max_length=20)),
                ('song_url', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='library.library')),
                ('prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='prompt.prompt')),
            ],
            options={
                'db_table': 'song',
                'ordering': ['created_at'],
            },
        ),
    ]
