# Generated by Django 6.0.3 on 2026-04-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='generation_status',
        ),
    ]
