# Generated by Django 6.0.3 on 2026-04-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_remove_song_generation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
