# Generated by Django 6.0.3 on 2026-04-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_song_generation_status_alter_song_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='generation_status',
        ),
    ]
