# Generated by Django 6.0.3 on 2026-04-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_remove_song_generation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='shared_link',
            new_name='shared_code',
        ),
    ]
